### ISSUE TITLE
Updated Certs but image did not build correctly on quay.io

### ISSUE THREAD

**Issue by s0undt3ch** [rst0git/virt-minion#6]
How can I help?

**Comment by rst0git** [comment]
For some reason I had to reauthorize the build action. I have updated the base image to Fedora 36 and restarted the build now.
@s0undt3ch I also added you as an admin in the https://quay.io/repository/rst0git/virt-minion repository.

**Comment by s0undt3ch** [comment]
Thank You @rst0git.

In an effort to bring all our CI dependencies into our own "umbrella"(well, when possible ), the image used now is from https://github.com/saltstack/virt-minion which is actually a fork of your repo.

So I'll pull in your latest changes into the fork next week.

Thank You for making the virt support testable.

**Comment by rst0git** [comment]
@s0undt3ch If it possible to rename `saltstack/virt-minion`, I would be happy to transfer the ownership of this repository to https://github.com/saltstack.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by s0undt3ch** [comment]
Renamed. Thank You for generosity.

**Comment by rst0git** [comment]
When I try to transfer this repository, GitHub shows the following error:
> saltstack already has a repository in the rst0git/virt-minion network and You don’t have the permission to create public repositories on saltstack

**Comment by s0undt3ch** [comment]
@rst0git All of your git history was preserved and we now host our CI containers under https://github.com/saltstack/salt-ci-containers
